let characterAmountRange = document.getElementById("character-amount-range")
let characterAmountNumber = document.getElementById("character-amount-number")
let form = document.getElementById("passWordGeneratorForm")
let uppercaseElement = document.getElementById("uppercase")
let numbersElement = document.getElementById("numbers")
let symbolsElement = document.getElementById("symbols")

// STILL NEED TO SHORTEN CODE

let char = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "0","1","2","3","4","5","6","7","8","9", "~","`","!","@","#","$","%","^","&","*","(",")","_","-","+","=","{","[","}","]","|",";","'","<",",",">",".","?","/"]
let resultOne = document.querySelector("#result-1")
let resultTwo = document.querySelector("#result-2")
let resultThree = document.querySelector("#result-3")
let resultFour = document.querySelector("#result-4")

function generatePasswords20()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords19()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords18()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords17()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords16()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords15()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords14()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords13()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords12()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}
function generatePasswords11()    {
    resultOne.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultTwo.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultThree.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
    resultFour.textContent = char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)] + char[Math.floor(Math.random() * char.length)];
}

characterAmountNumber.addEventListener("input", syncCharacterAmount)
characterAmountRange.addEventListener("input", syncCharacterAmount)

// links character count input and sliders
function syncCharacterAmount(e) {
    let value = e.target.value
    characterAmountNumber.value = value
    characterAmountRange.value = value
    console.log(value)

    if (value == 11) {
        generatePasswords11()
    } if (value == 12) {
        generatePasswords12()
    } if (value == 13) {
        generatePasswords13()
    } if (value == 14) {
        generatePasswords14()
    } if (value == 15) {
        generatePasswords15()
    } if (value == 16) {
        generatePasswords16()
    } if (value == 17) {
        generatePasswords17()
    } if (value == 18) {
        generatePasswords18()
    } if (value == 19) {
        generatePasswords19()
    } if (value == 20) {
        generatePasswords20()
    } 
}

// prevents submit button from refreshing page (prevent default) 
form.addEventListener("submit", e => {
    e.preventDefault()
})


// light and dark theme setup
var icon = document.getElementById("icon");
icon.onclick = function()   {
    document.body.classList.toggle("light-theme");
    if(document.body.classList.contains("light-theme")){
        icon.src = "./image/moon.png";
    } else  {
        icon.src = "./image/sun.png";
    }
}